### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by stuffmattdoes** [stuffmattdoes/e-ink-display#1]
**Os:**
Raspbian GNU/Linux 8 (jessie)

**Python Version**
Python 3.4.2

**Full error**
```Traceback (most recent call last):
  File "pi-cal.py", line 399, in <module>
    main()
  File "pi-cal.py", line 41, in main
    render()
  File "pi-cal.py", line 396, in render
    epd.display_frame(epd.get_frame_buffer(image))
  File "/home/pi/python_programs/pi-cal/src/epd7in5.py", line 159, in get_frame_buffer
    buf = [0x00] * (self.width * self.height / 8)
TypeError: can't multiply sequence by non-int of type 'float'
```

**Reproduce**
Ensure you've got all the necessary packages installed as detailed in this project's root `readme`
run: `cd src && python3 pi-cal.py`

**Comment by stuffmattdoes** [comment]
# Cause
The difference is in how integer division is handled between `Python 2.7` vs. `Python 3.4`.

Refer to `epd7in5.py` file, specifically the `get_frame_buffer` function @ line 158.

```Python
def get_frame_buffer(self, image):
        buf = [0x00] * (self.width * self.height / 8)

        # Set buffer to value of Python Imaging Library image.
        # Image must be in mode 1.
        image_monocolor = image.convert('1')
        imwidth, imheight = image_monocolor.size
        if imwidth != self.width or imheight != self.height:
            raise ValueError('Image must be same dimensions as display \
                ({0}x{1}).' .format(self.width, self.height))

        pixels = image_monocolor.load()
        for y in range(self.height):
            for x in range(self.width):
                # Set the bits for the column of pixels at the current position.
                if pixels[x, y] != 0:
                    buf[(x + y * self.width) / 8] |= 0x80 >> (x % 8)
        return buf
```

There are a few instances where we're multiplying the display with x its height / 8. Here's how that looks between python versions:

```Python
# Python 2.7
(640 * 384 / 8) # = 30720

# Python 3.4
(640 * 384 / 8) # = 30720.0
```

# Fix
Simply using the double slash `//` division operator will yield an integer as expected in both version of python.

We want our division to return an `int` in order to multiply by a `byte` array. That cannot be done with a `float`.

```Python
# Python 2.7
(640 * 384 // 8) # = 30720

# Python 3.4
(640 * 384 // 8) # = 30720
```

**Comment by stuffmattdoes** [comment]
Alternatively, you could encapsulate each arithmetic and cast to an int:
```Python
buf = [0x00] * (int(self.width * self.height / 8))
...
buf[int((x + y * self.width) / 8)] |= 0x80 >> (x % 8)
```
